# Generated by Django 3.1.7 on 2021-04-06 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigdataCount',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('jandt', models.IntegerField(default=0)),
                ('candd', models.IntegerField(default=0)),
                ('chfood', models.IntegerField(default=0)),
                ('chicken', models.IntegerField(default=0)),
                ('pizza', models.IntegerField(default=0)),
                ('fastfood', models.IntegerField(default=0)),
                ('bunfood', models.IntegerField(default=0)),
                ('jpfood', models.IntegerField(default=0)),
                ('krfood', models.IntegerField(default=0)),
                ('jandb', models.IntegerField(default=0)),
                ('aanda', models.IntegerField(default=0)),
                ('etc', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'BigdataCounts',
            },
        ),
        migrations.CreateModel(
            name='BigdataProcess',
            fields=[
                ('num', models.FloatField(primary_key=True, serialize=False)),
                ('jandt', models.FloatField(default=0)),
                ('candd', models.FloatField(default=0)),
                ('chfood', models.FloatField(default=0)),
                ('chicken', models.FloatField(default=0)),
                ('pizza', models.FloatField(default=0)),
                ('fastfood', models.FloatField(default=0)),
                ('bunfood', models.FloatField(default=0)),
                ('jpfood', models.FloatField(default=0)),
                ('krfood', models.FloatField(default=0)),
                ('jandb', models.FloatField(default=0)),
                ('aanda', models.FloatField(default=0)),
                ('etc', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'BigdataProcesss',
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('lid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('landmark_name', models.CharField(max_length=200)),
                ('addr', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('logitude', models.CharField(max_length=200, null=True)),
                ('facility', models.CharField(max_length=200, null=True)),
                ('park', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('tel', models.CharField(max_length=200, null=True)),
                ('theme', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'landmarks',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('mid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=39, null=True)),
                ('menu_name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=30, null=True)),
                ('num', models.CharField(max_length=30, null=True)),
                ('total_score', models.CharField(max_length=30, null=True)),
                ('content', models.TextField()),
                ('reg_time', models.TextField()),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='RScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(max_length=50, null=True)),
                ('t2', models.CharField(max_length=50, null=True)),
                ('score', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'db_table': 'rScoreTables',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('sid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('logitude', models.CharField(max_length=100, null=True)),
                ('review_cnt', models.IntegerField(default=0)),
                ('review_sum', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100, null=True)),
                ('review_avg', models.DecimalField(decimal_places=2,max_digits=4)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='ZzimLandCourse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=30, null=True)),
                ('lid1', models.CharField(max_length=30, null=True)),
                ('lid2', models.CharField(max_length=30, null=True)),
                ('lid3', models.CharField(max_length=30, null=True)),
                ('lid4', models.CharField(max_length=30, null=True)),
                ('isSaved', models.CharField(max_length=30, null=True)),
                ('savedDate', models.CharField(default=datetime.datetime(2021, 4, 7, 1, 26, 11, 238602), max_length=100, null=True)),
            ],
            options={
                'db_table': 'zzimLandCourses',
            },
        ),
        migrations.CreateModel(
            name='ZzimStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=30, null=True)),
                ('sid', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'zzimStores',
            },
        ),
        migrations.CreateModel(
            name='ZzimStoreCourse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=30, null=True)),
                ('sidB', models.CharField(max_length=30, null=True)),
                ('isSavedB', models.CharField(max_length=30, null=True)),
                ('sidL', models.CharField(max_length=30, null=True)),
                ('isSavedL', models.CharField(max_length=30, null=True)),
                ('sidD', models.CharField(max_length=30, null=True)),
                ('isSavedD', models.CharField(max_length=30, null=True)),
                ('savedDate', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'zzimStoreCourses',
            },
        ),
    ]
