# Generated by Django 3.1.7 on 2021-04-02 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendroad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzimlandcourse',
            name='savedDate',
            field=models.CharField(default=datetime.datetime(2021, 4, 2, 21, 48, 50, 878416), max_length=100, null=True),
        ),
    ]
