# Generated by Django 3.1.7 on 2021-04-06 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendroad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigdatacount',
            name='sumcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zzimlandcourse',
            name='savedDate',
            field=models.CharField(default=datetime.datetime(2021, 4, 7, 1, 27, 4, 510422), max_length=100, null=True),
        ),
    ]
