# Generated by Django 3.1.7 on 2021-04-05 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendroad', '0003_auto_20210403_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzimlandcourse',
            name='savedDate',
            field=models.CharField(default=datetime.datetime(2021, 4, 5, 21, 3, 21, 962459), max_length=100, null=True),
        ),
    ]
