# Generated by Django 3.1.7 on 2021-04-05 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendroad', '0004_auto_20210405_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zzimlandcourse',
            name='savedDate',
            field=models.CharField(default=datetime.datetime(2021, 4, 5, 23, 55, 47, 697543), max_length=100, null=True),
        ),
    ]
