# Generated by Django 3.1.7 on 2021-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.BooleanField()),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
